package com.yukimt.katakana

import com.yukimt.katakana.tokenizer.Kuromoji
import com.yukimt.katakana.alphabet.{English, Roman}
import com.yukimt.katakana.dictionary.MemoryDictionary

object Boot extends App {
  val eCon = new Converter(Kuromoji, English, Some(new MemoryDictionary))
  val rCon = new Converter(Kuromoji, Roman(), Some(new MemoryDictionary))
  println(eCon.convert("wine arrow branch taxi grape snake statue brush palace London zoo entrance gym tower Europe host dad elephant soup tie fox jeans jam suit ticket Canada fence England Asia hall forest mom engineer policeman toy umbrella frog bottle ink sofa bomb China desert Australia beach theater tent restaurant stranger driver enemy husband scientist bathroom runner artist visitor cousin sunset trade match death habit joy blood luck fishing president merchant barber army painter reporter God century goal training disease tour exam flight film mind pain crowd guide queen pal captain neighbor prince midnight play tear concert action festival pop thought promise accident custom waste use reply race stay valley silver heaven ocean soil billion couple area calendar signal discussion sign volleyball answer stop courage iron universe silk wave root smoke course shade prize list page report step secret quiz care rush plant gas climate jewel rainbow weather model point railway mark  bowl lip net melon poem menu gram cent address damage sort reason kilometer middle shock centimeter zone toast curtain juice honey goods sense type symbol energy position gray bit matter power sentence yen grade plate cheese can treasure hole price problem fact beauty pair percent case spelling meaning square youth order wonder smell kiss cross select awake fill print succeed receive date raise exercise return destroy belong realize sound invent solve hurt knock touch miss reach hand choose share copy boil train cover break please explain bake discuss lie shake save hit mix blow shoot fight introduce row drop marry interested ashamed blind gentle pleased monthly open flat musical noisy holy lonely merry living personal necessary wild outside fresh healthy lovely dumb modern peaceful raw international back natural lost quick first second third forth fifth sixth seventh eighth ninth tenth eleventh twelfth thirteenth fourteenth fifteenth sixteenth seventeenth eighteenth nineteenth twentieth thirtieth unhappy lazy brave pale simple daily exciting senior safe national Chinese another than while but when during excited fat funny cute sleepy delicious calm tiny final central wet common because and however hello after crazy fond friendly silent close real certain wrong weekly snowy whole if although though or between tonight ever once finally straight everywhere down pretty besides maybe surely certainly easily neither alone hard forever suddenly especially quickly long away abroad ahead all almost indeed else anyway either gently probably happily then twice still recently off across round just quite perhaps even quietly fine carefully never really "))
}
